### ISSUE TITLE
Functionality seems to be broken

### ISSUE THREAD

**Issue by Nebula-Developer** [aekaisato/cr-force-hardsub#1]
Are there any plans to update this? It does not seem to work on the latest version of crunchyroll/firefox.

**Comment by aekaisato** [comment]
Sorry for the late response. Have you checked the permissions for extension?

![image](https://github.com/aekaisato/cr-force-hardsub/assets/35282290/94bce99a-8c8f-4ed9-97a6-d5b6af53ee3a)

Due to some Manifest V3 stuff I wasn't aware of, all permissions are marked as optional, and therefore you need to manually grant permissions. At some point I plan to add a prompt for this in the extension itself, but since this is a random side thing I threw together, it's not super high priority.

**Comment by Nebula-Developer** [comment]
Just tried it again with the fixed permissions. Works brilliantly! Thanks.
